# Generated by Django 3.0.8 on 2020-08-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200724_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Barənizdə:', null=True, verbose_name='Barəmdə'),
        ),
    ]
